### YamlMime:ManagedReference
items:
- uid: com.azure.core.exception.AzureException
  id: AzureException
  parent: com.azure.core.exception
  children:
  - com.azure.core.exception.AzureException.AzureException(final String)
  - com.azure.core.exception.AzureException.AzureException(final String,final Throwable)
  href: com.azure.core.exception.AzureException.yml
  langs:
  - java
  name: AzureException
  nameWithType: AzureException
  fullName: com.azure.core.exception.AzureException
  type: Class
  source:
    remote: &o0
      path: sdk/core/azure-core/src/main/java/com/azure/core/exception/AzureException.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: sdk/core/azure-core/src/main/java/com/azure/core/exception/AzureException.java
    startLine: 12
  package: com.azure.core.exception
  summary: "<p>The base exception type for all Azure-related exceptions.</p>\r\n<p></p>"
  syntax:
    content: public class AzureException
  inheritance:
  - java.lang.Object
  - RuntimeException
- uid: com.azure.core.exception.AzureException.AzureException(final String)
  id: AzureException(final String)
  parent: com.azure.core.exception.AzureException
  href: com.azure.core.exception.AzureException.yml
  langs:
  - java
  name: AzureException(final String message)
  nameWithType: AzureException.AzureException(final String message)
  fullName: com.azure.core.exception.AzureException.AzureException(final String message)
  overload: com.azure.core.exception.AzureException.AzureException*
  type: Constructor
  source:
    remote: *o0
    path: sdk/core/azure-core/src/main/java/com/azure/core/exception/AzureException.java
    startLine: 19
  package: com.azure.core.exception
  summary: "<p>Initializes a new instance of the AzureException class.</p>\r\n<p></p>"
  syntax:
    content: public AzureException(final String message)
    parameters:
    - id: message
      type: 3d93591e
      description: <p>the exception message. </p>
- uid: com.azure.core.exception.AzureException.AzureException(final String,final Throwable)
  id: AzureException(final String,final Throwable)
  parent: com.azure.core.exception.AzureException
  href: com.azure.core.exception.AzureException.yml
  langs:
  - java
  name: AzureException(final String message, final Throwable cause)
  nameWithType: AzureException.AzureException(final String message, final Throwable cause)
  fullName: com.azure.core.exception.AzureException.AzureException(final String message, final Throwable cause)
  overload: com.azure.core.exception.AzureException.AzureException*
  type: Constructor
  source:
    remote: *o0
    path: sdk/core/azure-core/src/main/java/com/azure/core/exception/AzureException.java
    startLine: 29
  package: com.azure.core.exception
  summary: "<p>Initializes a new instance of the AzureException class.</p>\r\n<p></p>"
  syntax:
    content: public AzureException(final String message, final Throwable cause)
    parameters:
    - id: message
      type: 3d93591e
      description: <p>the exception message. </p>
    - id: cause
      type: fa00b19f
      description: <p>the Throwable which caused the creation of this AzureException. </p>
references:
- uid: 3d93591e
  spec.java:
  - name: final String
    fullName: final String
- uid: com.azure.core.exception.AzureException.AzureException*
  name: AzureException
  nameWithType: AzureException.AzureException
  fullName: com.azure.core.exception.AzureException.AzureException
  package: com.azure.core.exception
- uid: fa00b19f
  spec.java:
  - name: final Throwable
    fullName: final Throwable
- uid: com.azure.core.amqp.exception.AmqpException
  parent: com.azure.core.amqp.exception
  href: com.azure.core.amqp.exception.AmqpException.yml
  name: AmqpException
  nameWithType: AmqpException
  fullName: com.azure.core.amqp.exception.AmqpException
  type: Class
  summary: "<p>General exception for AMQP related failures.</p>\r\n<p></p>"
  syntax:
    content: public class AmqpException extends AzureException
- uid: com.azure.core.exception.HttpRequestException
  parent: com.azure.core.exception
  href: com.azure.core.exception.HttpRequestException.yml
  name: HttpRequestException
  nameWithType: HttpRequestException
  fullName: com.azure.core.exception.HttpRequestException
  type: Class
  summary: "<p>The exception occurred while attempting to connect a socket to a azure service address and port. Typically, the connection was refused remotely (e.g., no process is listening on the azure service address/port).</p>\r\n<p>These errors are safe to retry. </p>"
  syntax:
    content: public class HttpRequestException
- uid: com.azure.core.exception.HttpResponseException
  parent: com.azure.core.exception
  href: com.azure.core.exception.HttpResponseException.yml
  name: HttpResponseException
  nameWithType: HttpResponseException
  fullName: com.azure.core.exception.HttpResponseException
  type: Class
  summary: "<p>The exception thrown when an unsuccessful response is received with http status code (e.g. 3XX, 4XX, 5XX) from the service request. </p>"
  syntax:
    content: public class HttpResponseException
- uid: com.azure.core.exception.ServiceResponseException
  parent: com.azure.core.exception
  href: com.azure.core.exception.ServiceResponseException.yml
  name: ServiceResponseException
  nameWithType: ServiceResponseException
  fullName: com.azure.core.exception.ServiceResponseException
  type: Class
  summary: "<p>A runtime exception indicating service response failure caused by one of the following scenarios: 1. The request was sent, but the client failed to understand the response. (Not in the right format, partial response etc.) 2. The connection may have timed out. These errors can be retried for idempotent or safe operations. </p>"
  syntax:
    content: public class ServiceResponseException
