### YamlMime:JavaType
uid: "com.azure.analytics.synapse.artifacts.models.CloudErrorException"
fullName: "com.azure.analytics.synapse.artifacts.models.CloudErrorException"
name: "CloudErrorException"
nameWithType: "CloudErrorException"
summary: "Exception thrown for an invalid response with Cloud<wbr>Error information."
inheritances:
- "<xref href=\"java.lang.Object?displayProperty=fullName\" data-throw-if-not-resolved=\"False\" />"
- "<xref href=\"java.lang.Throwable?displayProperty=fullName\" data-throw-if-not-resolved=\"False\" />"
- "<xref href=\"java.lang.Exception?displayProperty=fullName\" data-throw-if-not-resolved=\"False\" />"
- "<xref href=\"java.lang.RuntimeException?displayProperty=fullName\" data-throw-if-not-resolved=\"False\" />"
- "<xref href=\"com.azure.core.exception.AzureException?displayProperty=fullName\" data-throw-if-not-resolved=\"False\" />"
- "<xref href=\"com.azure.core.exception.HttpResponseException?displayProperty=fullName\" data-throw-if-not-resolved=\"False\" />"
inheritedMembers:
- "com.azure.core.exception.HttpResponseException.getResponse()"
- "com.azure.core.exception.HttpResponseException.getValue()"
- "java.lang.Object.clone()"
- "java.lang.Object.equals(java.lang.Object)"
- "java.lang.Object.finalize()"
- "java.lang.Object.getClass()"
- "java.lang.Object.hashCode()"
- "java.lang.Object.notify()"
- "java.lang.Object.notifyAll()"
- "java.lang.Object.wait()"
- "java.lang.Object.wait(long)"
- "java.lang.Object.wait(long,int)"
- "java.lang.Throwable.addSuppressed(java.lang.Throwable)"
- "java.lang.Throwable.fillInStackTrace()"
- "java.lang.Throwable.getCause()"
- "java.lang.Throwable.getLocalizedMessage()"
- "java.lang.Throwable.getMessage()"
- "java.lang.Throwable.getStackTrace()"
- "java.lang.Throwable.getSuppressed()"
- "java.lang.Throwable.initCause(java.lang.Throwable)"
- "java.lang.Throwable.printStackTrace()"
- "java.lang.Throwable.printStackTrace(java.io.PrintStream)"
- "java.lang.Throwable.printStackTrace(java.io.PrintWriter)"
- "java.lang.Throwable.setStackTrace(java.lang.StackTraceElement[])"
- "java.lang.Throwable.toString()"
syntax: "public final class CloudErrorException extends HttpResponseException"
constructors:
- uid: "com.azure.analytics.synapse.artifacts.models.CloudErrorException.CloudErrorException(java.lang.String,com.azure.core.http.HttpResponse)"
  fullName: "com.azure.analytics.synapse.artifacts.models.CloudErrorException.CloudErrorException(String message, HttpResponse response)"
  name: "CloudErrorException(String message, HttpResponse response)"
  nameWithType: "CloudErrorException.CloudErrorException(String message, HttpResponse response)"
  summary: "Initializes a new instance of the Cloud<wbr>Error<wbr>Exception class."
  parameters:
  - description: "the exception message or the response content if a message is not available."
    name: "message"
    type: "<xref href=\"java.lang.String?alt=java.lang.String&text=String\" data-throw-if-not-resolved=\"False\" />"
  - description: "the HTTP response."
    name: "response"
    type: "<xref href=\"com.azure.core.http.HttpResponse?alt=com.azure.core.http.HttpResponse&text=HttpResponse\" data-throw-if-not-resolved=\"False\" />"
  syntax: "public CloudErrorException(String message, HttpResponse response)"
  desc: "Initializes a new instance of the CloudErrorException class."
- uid: "com.azure.analytics.synapse.artifacts.models.CloudErrorException.CloudErrorException(java.lang.String,com.azure.core.http.HttpResponse,com.azure.analytics.synapse.artifacts.models.CloudError)"
  fullName: "com.azure.analytics.synapse.artifacts.models.CloudErrorException.CloudErrorException(String message, HttpResponse response, CloudError value)"
  name: "CloudErrorException(String message, HttpResponse response, CloudError value)"
  nameWithType: "CloudErrorException.CloudErrorException(String message, HttpResponse response, CloudError value)"
  summary: "Initializes a new instance of the Cloud<wbr>Error<wbr>Exception class."
  parameters:
  - description: "the exception message or the response content if a message is not available."
    name: "message"
    type: "<xref href=\"java.lang.String?alt=java.lang.String&text=String\" data-throw-if-not-resolved=\"False\" />"
  - description: "the HTTP response."
    name: "response"
    type: "<xref href=\"com.azure.core.http.HttpResponse?alt=com.azure.core.http.HttpResponse&text=HttpResponse\" data-throw-if-not-resolved=\"False\" />"
  - description: "the deserialized response value."
    name: "value"
    type: "<xref href=\"com.azure.analytics.synapse.artifacts.models.CloudError?alt=com.azure.analytics.synapse.artifacts.models.CloudError&text=CloudError\" data-throw-if-not-resolved=\"False\" />"
  syntax: "public CloudErrorException(String message, HttpResponse response, CloudError value)"
  desc: "Initializes a new instance of the CloudErrorException class."
methods:
- uid: "com.azure.analytics.synapse.artifacts.models.CloudErrorException.getValue()"
  fullName: "com.azure.analytics.synapse.artifacts.models.CloudErrorException.getValue()"
  name: "getValue()"
  nameWithType: "CloudErrorException.getValue()"
  overridden: "com.azure.core.exception.HttpResponseException.getValue()"
  syntax: "public CloudError getValue()"
  returns:
    type: "<xref href=\"com.azure.analytics.synapse.artifacts.models.CloudError?alt=com.azure.analytics.synapse.artifacts.models.CloudError&text=CloudError\" data-throw-if-not-resolved=\"False\" />"
type: "class"
desc: "Exception thrown for an invalid response with CloudError information."
metadata: {}
package: "com.azure.analytics.synapse.artifacts.models"
artifact: com.azure:azure-analytics-synapse-artifacts:1.0.0-beta.10
