### YamlMime:JavaType
uid: "com.azure.core.exception.ClientAuthenticationException"
fullName: "com.azure.core.exception.ClientAuthenticationException"
name: "ClientAuthenticationException"
nameWithType: "ClientAuthenticationException"
summary: "The exception thrown when failed to authenticate the client request with status code of 4XX, typically 401 unauthorized."
inheritances:
- "<xref href=\"java.lang.Object?displayProperty=fullName\" data-throw-if-not-resolved=\"False\" />"
- "<xref href=\"java.lang.Throwable?displayProperty=fullName\" data-throw-if-not-resolved=\"False\" />"
- "<xref href=\"java.lang.Exception?displayProperty=fullName\" data-throw-if-not-resolved=\"False\" />"
- "<xref href=\"java.lang.RuntimeException?displayProperty=fullName\" data-throw-if-not-resolved=\"False\" />"
- "<xref href=\"com.azure.core.exception.AzureException?displayProperty=fullName\" data-throw-if-not-resolved=\"False\" />"
- "<xref href=\"com.azure.core.exception.HttpResponseException?displayProperty=fullName\" data-throw-if-not-resolved=\"False\" />"
inheritedMembers:
- "com.azure.core.exception.HttpResponseException.getResponse()"
- "com.azure.core.exception.HttpResponseException.getValue()"
- "java.lang.Object.clone()"
- "java.lang.Object.equals(java.lang.Object)"
- "java.lang.Object.finalize()"
- "java.lang.Object.getClass()"
- "java.lang.Object.hashCode()"
- "java.lang.Object.notify()"
- "java.lang.Object.notifyAll()"
- "java.lang.Object.wait()"
- "java.lang.Object.wait(long)"
- "java.lang.Object.wait(long,int)"
- "java.lang.Throwable.addSuppressed(java.lang.Throwable)"
- "java.lang.Throwable.fillInStackTrace()"
- "java.lang.Throwable.getCause()"
- "java.lang.Throwable.getLocalizedMessage()"
- "java.lang.Throwable.getMessage()"
- "java.lang.Throwable.getStackTrace()"
- "java.lang.Throwable.getSuppressed()"
- "java.lang.Throwable.initCause(java.lang.Throwable)"
- "java.lang.Throwable.printStackTrace()"
- "java.lang.Throwable.printStackTrace(java.io.PrintStream)"
- "java.lang.Throwable.printStackTrace(java.io.PrintWriter)"
- "java.lang.Throwable.setStackTrace(java.lang.StackTraceElement[])"
- "java.lang.Throwable.toString()"
syntax: "public class ClientAuthenticationException extends HttpResponseException"
constructors:
- uid: "com.azure.core.exception.ClientAuthenticationException.ClientAuthenticationException(java.lang.String,com.azure.core.http.HttpResponse)"
  fullName: "com.azure.core.exception.ClientAuthenticationException.ClientAuthenticationException(String message, HttpResponse response)"
  name: "ClientAuthenticationException(String message, HttpResponse response)"
  nameWithType: "ClientAuthenticationException.ClientAuthenticationException(String message, HttpResponse response)"
  summary: "Initializes a new instance of the <xref uid=\"com.azure.core.exception.ClientAuthenticationException\" data-throw-if-not-resolved=\"false\" data-raw-source=\"ClientAuthenticationException\"></xref> class."
  parameters:
  - description: "The exception message or the response content if a message is not available."
    name: "message"
    type: "<xref href=\"java.lang.String?alt=java.lang.String&text=String\" data-throw-if-not-resolved=\"False\" />"
  - description: "The HTTP response with the authorization failure."
    name: "response"
    type: "<xref href=\"com.azure.core.http.HttpResponse?alt=com.azure.core.http.HttpResponse&text=HttpResponse\" data-throw-if-not-resolved=\"False\" />"
  syntax: "public ClientAuthenticationException(String message, HttpResponse response)"
  desc: "Initializes a new instance of the <xref uid=\"com.azure.core.exception.ClientAuthenticationException\" data-throw-if-not-resolved=\"false\" data-raw-source=\"ClientAuthenticationException\"></xref> class."
- uid: "com.azure.core.exception.ClientAuthenticationException.ClientAuthenticationException(java.lang.String,com.azure.core.http.HttpResponse,java.lang.Object)"
  fullName: "com.azure.core.exception.ClientAuthenticationException.ClientAuthenticationException(String message, HttpResponse response, Object value)"
  name: "ClientAuthenticationException(String message, HttpResponse response, Object value)"
  nameWithType: "ClientAuthenticationException.ClientAuthenticationException(String message, HttpResponse response, Object value)"
  summary: "Initializes a new instance of the <xref uid=\"com.azure.core.exception.ClientAuthenticationException\" data-throw-if-not-resolved=\"false\" data-raw-source=\"ClientAuthenticationException\"></xref> class."
  parameters:
  - description: "The exception message or the response content if a message is not available."
    name: "message"
    type: "<xref href=\"java.lang.String?alt=java.lang.String&text=String\" data-throw-if-not-resolved=\"False\" />"
  - description: "The HTTP response with the authorization failure."
    name: "response"
    type: "<xref href=\"com.azure.core.http.HttpResponse?alt=com.azure.core.http.HttpResponse&text=HttpResponse\" data-throw-if-not-resolved=\"False\" />"
  - description: "The deserialized HTTP response value."
    name: "value"
    type: "<xref href=\"java.lang.Object?alt=java.lang.Object&text=Object\" data-throw-if-not-resolved=\"False\" />"
  syntax: "public ClientAuthenticationException(String message, HttpResponse response, Object value)"
  desc: "Initializes a new instance of the <xref uid=\"com.azure.core.exception.ClientAuthenticationException\" data-throw-if-not-resolved=\"false\" data-raw-source=\"ClientAuthenticationException\"></xref> class."
- uid: "com.azure.core.exception.ClientAuthenticationException.ClientAuthenticationException(java.lang.String,com.azure.core.http.HttpResponse,java.lang.Throwable)"
  fullName: "com.azure.core.exception.ClientAuthenticationException.ClientAuthenticationException(String message, HttpResponse response, Throwable cause)"
  name: "ClientAuthenticationException(String message, HttpResponse response, Throwable cause)"
  nameWithType: "ClientAuthenticationException.ClientAuthenticationException(String message, HttpResponse response, Throwable cause)"
  summary: "Initializes a new instance of the <xref uid=\"com.azure.core.exception.ClientAuthenticationException\" data-throw-if-not-resolved=\"false\" data-raw-source=\"ClientAuthenticationException\"></xref> class."
  parameters:
  - description: "The exception message or the response content if a message is not available."
    name: "message"
    type: "<xref href=\"java.lang.String?alt=java.lang.String&text=String\" data-throw-if-not-resolved=\"False\" />"
  - description: "The HTTP response with the authorization failure."
    name: "response"
    type: "<xref href=\"com.azure.core.http.HttpResponse?alt=com.azure.core.http.HttpResponse&text=HttpResponse\" data-throw-if-not-resolved=\"False\" />"
  - description: "The <xref uid=\"java.lang.Throwable\" data-throw-if-not-resolved=\"false\" data-raw-source=\"Throwable\"></xref> which caused the creation of this exception."
    name: "cause"
    type: "<xref href=\"java.lang.Throwable?alt=java.lang.Throwable&text=Throwable\" data-throw-if-not-resolved=\"False\" />"
  syntax: "public ClientAuthenticationException(String message, HttpResponse response, Throwable cause)"
  desc: "Initializes a new instance of the <xref uid=\"com.azure.core.exception.ClientAuthenticationException\" data-throw-if-not-resolved=\"false\" data-raw-source=\"ClientAuthenticationException\"></xref> class."
type: "class"
desc: "The exception thrown when failed to authenticate the client request with status code of 4XX, typically 401 unauthorized. A runtime exception indicating request authorization failure caused by one of the following scenarios:\n\n *  A client did not send the required authorization credentials to access the requested resource, i.e. Authorization HTTP header is missing in the request\n *  If the request contains the HTTP Authorization header, then the exception indicates that authorization has been refused for the credentials contained in the request header."
metadata: {}
package: "com.azure.core.exception"
artifact: com.azure:azure-core:1.22.0-beta.1
