### YamlMime:JavaMember
uid: "org.apache.hc.core5.http.nio.support.AbstractAsyncPushHandler.handleError*"
fullName: "org.apache.hc.core5.http.nio.support.AbstractAsyncPushHandler<T>.handleError"
name: "handleError"
nameWithType: "AbstractAsyncPushHandler<T>.handleError"
members:
- uid: "org.apache.hc.core5.http.nio.support.AbstractAsyncPushHandler.handleError(org.apache.hc.core5.http.HttpRequest,java.lang.Exception)"
  fullName: "org.apache.hc.core5.http.nio.support.AbstractAsyncPushHandler<T>.handleError(HttpRequest promise, Exception cause)"
  name: "handleError(HttpRequest promise, Exception cause)"
  nameWithType: "AbstractAsyncPushHandler<T>.handleError(HttpRequest promise, Exception cause)"
  summary: "Triggered to handle the exception thrown while processing a push response."
  parameters:
  - description: "the promised request message."
    name: "promise"
    type: "<xref href=\"org.apache.hc.core5.http.HttpRequest?alt=org.apache.hc.core5.http.HttpRequest&text=HttpRequest\" data-throw-if-not-resolved=\"False\" />"
  - description: "the cause of error."
    name: "cause"
    type: "<xref href=\"java.lang.Exception?alt=java.lang.Exception&text=Exception\" data-throw-if-not-resolved=\"False\" />"
  syntax: "protected void handleError(HttpRequest promise, Exception cause)"
type: "method"
metadata: {}
package: "org.apache.hc.core5.http.nio.support"
artifact: com.azure:azure-security-keyvault-jca:1.0.0-beta.2
