### YamlMime:JavaType
uid: "com.azure.core.test.models.NetworkCallError"
fullName: "com.azure.core.test.models.NetworkCallError"
name: "NetworkCallError"
nameWithType: "NetworkCallError"
summary: "This class represents a caught throwable during a network call. It is used to serialize exceptions that were thrown during the pipeline and deserialize them back into their actual throwable class when running in playback mode."
inheritances:
- "<xref href=\"java.lang.Object\" data-throw-if-not-resolved=\"False\" />"
inheritedMembers:
- "java.lang.Object.clone()"
- "java.lang.Object.equals(java.lang.Object)"
- "java.lang.Object.finalize()"
- "java.lang.Object.getClass()"
- "java.lang.Object.hashCode()"
- "java.lang.Object.notify()"
- "java.lang.Object.notifyAll()"
- "java.lang.Object.toString()"
- "java.lang.Object.wait()"
- "java.lang.Object.wait(long)"
- "java.lang.Object.wait(long,int)"
syntax: "public class NetworkCallError"
constructors:
- "com.azure.core.test.models.NetworkCallError.NetworkCallError()"
- "com.azure.core.test.models.NetworkCallError.NetworkCallError(java.lang.Throwable)"
methods:
- "com.azure.core.test.models.NetworkCallError.get()"
- "com.azure.core.test.models.NetworkCallError.setClassName(java.lang.String)"
- "com.azure.core.test.models.NetworkCallError.setErrorMessage(java.lang.String)"
- "com.azure.core.test.models.NetworkCallError.setThrowable(java.lang.Throwable)"
type: "class"
metadata: {}
package: "com.azure.core.test.models"
artifact: com.azure:azure-core-test:1.5.2
